/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AccessLog {
  'id' : string,
  'action' : string,
  'messageId' : string,
  'accessorId' : Principal,
  'timestamp' : bigint,
  'deviceFingerprint' : string,
}
export interface BehaviorProfile {
  'flagReason' : [] | [string],
  'userId' : Principal,
  'accessAttempts' : bigint,
  'flaggedAttempts' : bigint,
  'deviceFingerprints' : Array<string>,
  'lastAccessTime' : bigint,
  'isFlagged' : boolean,
}
export type ExternalBlob = Uint8Array;
export interface FileAttachment {
  'blob' : ExternalBlob,
  'fileName' : string,
  'fileSize' : bigint,
  'fileType' : string,
  'storageId' : string,
}
export interface MessageSummary {
  'id' : string,
  'expiresAt' : bigint,
  'isExpired' : boolean,
  'isViewed' : boolean,
  'createdAt' : bigint,
  'viewedAt' : [] | [bigint],
  'accessToken' : string,
  'recipientId' : Principal,
  'senderId' : Principal,
  'hasAttachment' : boolean,
}
export interface MessageView {
  'id' : string,
  'encryptedContent' : string,
  'contentKey' : string,
  'accessedAt' : bigint,
  'fileAttachment' : [] | [FileAttachment],
  'senderId' : Principal,
}
export interface Notification {
  'id' : string,
  'messageId' : string,
  'createdAt' : bigint,
  'isRead' : boolean,
  'message' : string,
  'recipientId' : Principal,
}
export type Result = { 'ok' : string } |
  { 'err' : string };
export type Result_1 = { 'ok' : boolean } |
  { 'err' : string };
export type Result_2 = { 'ok' : BehaviorProfile } |
  { 'err' : string };
export type Result_3 = { 'ok' : Array<AccessLog> } |
  { 'err' : string };
export type Result_4 = { 'ok' : Array<BehaviorProfile> } |
  { 'err' : string };
export type Result_5 = { 'ok' : Array<MessageSummary> } |
  { 'err' : string };
export type Result_6 = { 'ok' : MessageView } |
  { 'err' : string };
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  /**
   * / Monotonic counter for generating unique IDs and tokens
   */
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  /**
   * / Secondary index: messageId -> SecureMessage
   */
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'accessMessage' : ActorMethod<[string, string], Result_6>,
  'adminGetAllAccessLogs' : ActorMethod<[], Result_3>,
  'adminGetAllMessages' : ActorMethod<[], Result_5>,
  'adminGetFlaggedUsers' : ActorMethod<[], Result_4>,
  'adminSetAdminPrincipal' : ActorMethod<[Principal], Result_1>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteExpiredMessages' : ActorMethod<[], bigint>,
  'getAccessLogs' : ActorMethod<[string], Result_3>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyBehaviorProfile' : ActorMethod<[], Result_2>,
  'getMyInbox' : ActorMethod<[], Array<MessageSummary>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMySentMessages' : ActorMethod<[], Array<MessageSummary>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markNotificationRead' : ActorMethod<[string], Result_1>,
  'sendMessage' : ActorMethod<
    [Principal, string, string, bigint, [] | [FileAttachment]],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];