/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FileAttachment = IDL.Record({
  'blob' : ExternalBlob,
  'fileName' : IDL.Text,
  'fileSize' : IDL.Nat,
  'fileType' : IDL.Text,
  'storageId' : IDL.Text,
});
export const MessageView = IDL.Record({
  'id' : IDL.Text,
  'encryptedContent' : IDL.Text,
  'contentKey' : IDL.Text,
  'accessedAt' : IDL.Int,
  'fileAttachment' : IDL.Opt(FileAttachment),
  'senderId' : IDL.Principal,
});
export const Result_6 = IDL.Variant({ 'ok' : MessageView, 'err' : IDL.Text });
export const AccessLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'messageId' : IDL.Text,
  'accessorId' : IDL.Principal,
  'timestamp' : IDL.Int,
  'deviceFingerprint' : IDL.Text,
});
export const Result_3 = IDL.Variant({
  'ok' : IDL.Vec(AccessLog),
  'err' : IDL.Text,
});
export const MessageSummary = IDL.Record({
  'id' : IDL.Text,
  'expiresAt' : IDL.Int,
  'isExpired' : IDL.Bool,
  'isViewed' : IDL.Bool,
  'createdAt' : IDL.Int,
  'viewedAt' : IDL.Opt(IDL.Int),
  'accessToken' : IDL.Text,
  'recipientId' : IDL.Principal,
  'senderId' : IDL.Principal,
  'hasAttachment' : IDL.Bool,
});
export const Result_5 = IDL.Variant({
  'ok' : IDL.Vec(MessageSummary),
  'err' : IDL.Text,
});
export const BehaviorProfile = IDL.Record({
  'flagReason' : IDL.Opt(IDL.Text),
  'userId' : IDL.Principal,
  'accessAttempts' : IDL.Nat,
  'flaggedAttempts' : IDL.Nat,
  'deviceFingerprints' : IDL.Vec(IDL.Text),
  'lastAccessTime' : IDL.Int,
  'isFlagged' : IDL.Bool,
});
export const Result_4 = IDL.Variant({
  'ok' : IDL.Vec(BehaviorProfile),
  'err' : IDL.Text,
});
export const Result_1 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Result_2 = IDL.Variant({
  'ok' : BehaviorProfile,
  'err' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Text,
  'messageId' : IDL.Text,
  'createdAt' : IDL.Int,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'recipientId' : IDL.Principal,
});
export const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'accessMessage' : IDL.Func([IDL.Text, IDL.Text], [Result_6], []),
  'adminGetAllAccessLogs' : IDL.Func([], [Result_3], ['query']),
  'adminGetAllMessages' : IDL.Func([], [Result_5], ['query']),
  'adminGetFlaggedUsers' : IDL.Func([], [Result_4], ['query']),
  'adminSetAdminPrincipal' : IDL.Func([IDL.Principal], [Result_1], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteExpiredMessages' : IDL.Func([], [IDL.Nat], []),
  'getAccessLogs' : IDL.Func([IDL.Text], [Result_3], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyBehaviorProfile' : IDL.Func([], [Result_2], ['query']),
  'getMyInbox' : IDL.Func([], [IDL.Vec(MessageSummary)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMySentMessages' : IDL.Func([], [IDL.Vec(MessageSummary)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markNotificationRead' : IDL.Func([IDL.Text], [Result_1], []),
  'sendMessage' : IDL.Func(
      [IDL.Principal, IDL.Text, IDL.Text, IDL.Int, IDL.Opt(FileAttachment)],
      [Result],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FileAttachment = IDL.Record({
    'blob' : ExternalBlob,
    'fileName' : IDL.Text,
    'fileSize' : IDL.Nat,
    'fileType' : IDL.Text,
    'storageId' : IDL.Text,
  });
  const MessageView = IDL.Record({
    'id' : IDL.Text,
    'encryptedContent' : IDL.Text,
    'contentKey' : IDL.Text,
    'accessedAt' : IDL.Int,
    'fileAttachment' : IDL.Opt(FileAttachment),
    'senderId' : IDL.Principal,
  });
  const Result_6 = IDL.Variant({ 'ok' : MessageView, 'err' : IDL.Text });
  const AccessLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'messageId' : IDL.Text,
    'accessorId' : IDL.Principal,
    'timestamp' : IDL.Int,
    'deviceFingerprint' : IDL.Text,
  });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Vec(AccessLog), 'err' : IDL.Text });
  const MessageSummary = IDL.Record({
    'id' : IDL.Text,
    'expiresAt' : IDL.Int,
    'isExpired' : IDL.Bool,
    'isViewed' : IDL.Bool,
    'createdAt' : IDL.Int,
    'viewedAt' : IDL.Opt(IDL.Int),
    'accessToken' : IDL.Text,
    'recipientId' : IDL.Principal,
    'senderId' : IDL.Principal,
    'hasAttachment' : IDL.Bool,
  });
  const Result_5 = IDL.Variant({
    'ok' : IDL.Vec(MessageSummary),
    'err' : IDL.Text,
  });
  const BehaviorProfile = IDL.Record({
    'flagReason' : IDL.Opt(IDL.Text),
    'userId' : IDL.Principal,
    'accessAttempts' : IDL.Nat,
    'flaggedAttempts' : IDL.Nat,
    'deviceFingerprints' : IDL.Vec(IDL.Text),
    'lastAccessTime' : IDL.Int,
    'isFlagged' : IDL.Bool,
  });
  const Result_4 = IDL.Variant({
    'ok' : IDL.Vec(BehaviorProfile),
    'err' : IDL.Text,
  });
  const Result_1 = IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : BehaviorProfile, 'err' : IDL.Text });
  const Notification = IDL.Record({
    'id' : IDL.Text,
    'messageId' : IDL.Text,
    'createdAt' : IDL.Int,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'recipientId' : IDL.Principal,
  });
  const Result = IDL.Variant({ 'ok' : IDL.Text, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'accessMessage' : IDL.Func([IDL.Text, IDL.Text], [Result_6], []),
    'adminGetAllAccessLogs' : IDL.Func([], [Result_3], ['query']),
    'adminGetAllMessages' : IDL.Func([], [Result_5], ['query']),
    'adminGetFlaggedUsers' : IDL.Func([], [Result_4], ['query']),
    'adminSetAdminPrincipal' : IDL.Func([IDL.Principal], [Result_1], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteExpiredMessages' : IDL.Func([], [IDL.Nat], []),
    'getAccessLogs' : IDL.Func([IDL.Text], [Result_3], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyBehaviorProfile' : IDL.Func([], [Result_2], ['query']),
    'getMyInbox' : IDL.Func([], [IDL.Vec(MessageSummary)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMySentMessages' : IDL.Func([], [IDL.Vec(MessageSummary)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markNotificationRead' : IDL.Func([IDL.Text], [Result_1], []),
    'sendMessage' : IDL.Func(
        [IDL.Principal, IDL.Text, IDL.Text, IDL.Int, IDL.Opt(FileAttachment)],
        [Result],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };