/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Result_2 = {
    __kind__: "ok";
    ok: BehaviorProfile;
} | {
    __kind__: "err";
    err: string;
};
export type Result_6 = {
    __kind__: "ok";
    ok: MessageView;
} | {
    __kind__: "err";
    err: string;
};
export interface AccessLog {
    id: string;
    action: string;
    messageId: string;
    accessorId: Principal;
    timestamp: bigint;
    deviceFingerprint: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type Result_5 = {
    __kind__: "ok";
    ok: Array<MessageSummary>;
} | {
    __kind__: "err";
    err: string;
};
export type Result_1 = {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
};
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Result_4 = {
    __kind__: "ok";
    ok: Array<BehaviorProfile>;
} | {
    __kind__: "err";
    err: string;
};
export interface FileAttachment {
    blob: ExternalBlob;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    storageId: string;
}
export type Result = {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
};
export type Result_3 = {
    __kind__: "ok";
    ok: Array<AccessLog>;
} | {
    __kind__: "err";
    err: string;
};
export interface BehaviorProfile {
    flagReason?: string;
    userId: Principal;
    accessAttempts: bigint;
    flaggedAttempts: bigint;
    deviceFingerprints: Array<string>;
    lastAccessTime: bigint;
    isFlagged: boolean;
}
export interface Notification {
    id: string;
    messageId: string;
    createdAt: bigint;
    isRead: boolean;
    message: string;
    recipientId: Principal;
}
export interface MessageView {
    id: string;
    encryptedContent: string;
    contentKey: string;
    accessedAt: bigint;
    fileAttachment?: FileAttachment;
    senderId: Principal;
}
export interface MessageSummary {
    id: string;
    expiresAt: bigint;
    isExpired: boolean;
    isViewed: boolean;
    createdAt: bigint;
    viewedAt?: bigint;
    accessToken: string;
    recipientId: Principal;
    senderId: Principal;
    hasAttachment: boolean;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    /**
     * / Monotonic counter for generating unique IDs and tokens
     */
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    /**
     * / Secondary index: messageId -> SecureMessage
     */
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    accessMessage(accessToken: string, deviceFingerprint: string): Promise<Result_6>;
    adminGetAllAccessLogs(): Promise<Result_3>;
    adminGetAllMessages(): Promise<Result_5>;
    adminGetFlaggedUsers(): Promise<Result_4>;
    adminSetAdminPrincipal(newAdmin: Principal): Promise<Result_1>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteExpiredMessages(): Promise<bigint>;
    getAccessLogs(messageId: string): Promise<Result_3>;
    getCallerUserRole(): Promise<UserRole>;
    getMyBehaviorProfile(): Promise<Result_2>;
    getMyInbox(): Promise<Array<MessageSummary>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMySentMessages(): Promise<Array<MessageSummary>>;
    isCallerAdmin(): Promise<boolean>;
    markNotificationRead(notifId: string): Promise<Result_1>;
    sendMessage(recipientId: Principal, encryptedContent: string, contentKey: string, expiresInSeconds: bigint, fileAttachment: FileAttachment | null): Promise<Result>;
}
import type { AccessLog as _AccessLog, BehaviorProfile as _BehaviorProfile, ExternalBlob as _ExternalBlob, FileAttachment as _FileAttachment, MessageSummary as _MessageSummary, MessageView as _MessageView, Result as _Result, Result_1 as _Result_1, Result_2 as _Result_2, Result_3 as _Result_3, Result_4 as _Result_4, Result_5 as _Result_5, Result_6 as _Result_6, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async accessMessage(arg0: string, arg1: string): Promise<Result_6> {
        if (this.processError) {
            try {
                const result = await this.actor.accessMessage(arg0, arg1);
                return from_candid_Result_6_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.accessMessage(arg0, arg1);
            return from_candid_Result_6_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllAccessLogs(): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllAccessLogs();
                return from_candid_Result_3_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllAccessLogs();
            return from_candid_Result_3_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetAllMessages(): Promise<Result_5> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetAllMessages();
                return from_candid_Result_5_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetAllMessages();
            return from_candid_Result_5_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminGetFlaggedUsers(): Promise<Result_4> {
        if (this.processError) {
            try {
                const result = await this.actor.adminGetFlaggedUsers();
                return from_candid_Result_4_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminGetFlaggedUsers();
            return from_candid_Result_4_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSetAdminPrincipal(arg0: Principal): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetAdminPrincipal(arg0);
                return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetAdminPrincipal(arg0);
            return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n32(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteExpiredMessages(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteExpiredMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteExpiredMessages();
            return result;
        }
    }
    async getAccessLogs(arg0: string): Promise<Result_3> {
        if (this.processError) {
            try {
                const result = await this.actor.getAccessLogs(arg0);
                return from_candid_Result_3_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAccessLogs(arg0);
            return from_candid_Result_3_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyBehaviorProfile(): Promise<Result_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyBehaviorProfile();
                return from_candid_Result_2_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyBehaviorProfile();
            return from_candid_Result_2_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyInbox(): Promise<Array<MessageSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyInbox();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyInbox();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getMySentMessages(): Promise<Array<MessageSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySentMessages();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySentMessages();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markNotificationRead(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return from_candid_Result_1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: Principal, arg1: string, arg2: string, arg3: bigint, arg4: FileAttachment | null): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, await to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4));
                return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, arg2, arg3, await to_candid_opt_n38(this._uploadFile, this._downloadFile, arg4));
            return from_candid_Result_n42(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BehaviorProfile_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BehaviorProfile): BehaviorProfile {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileAttachment_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileAttachment): Promise<FileAttachment> {
    return await from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MessageSummary_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageSummary): MessageSummary {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
async function from_candid_MessageView_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageView): Promise<MessageView> {
    return await from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Result_2_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_2): Result_2 {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_Result_3_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_3): Result_3 {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Result_4_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_4): Result_4 {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_Result_5_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_5): Result_5 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Result_6_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_6): Promise<Result_6> {
    return await from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FileAttachment]): Promise<FileAttachment | null> {
    return value.length === 0 ? null : await from_candid_FileAttachment_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    encryptedContent: string;
    contentKey: string;
    accessedAt: bigint;
    fileAttachment: [] | [_FileAttachment];
    senderId: Principal;
}): Promise<{
    id: string;
    encryptedContent: string;
    contentKey: string;
    accessedAt: bigint;
    fileAttachment?: FileAttachment;
    senderId: Principal;
}> {
    return {
        id: value.id,
        encryptedContent: value.encryptedContent,
        contentKey: value.contentKey,
        accessedAt: value.accessedAt,
        fileAttachment: record_opt_to_undefined(await from_candid_opt_n12(_uploadFile, _downloadFile, value.fileAttachment)),
        senderId: value.senderId
    };
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: _ExternalBlob;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    storageId: string;
}): Promise<{
    blob: ExternalBlob;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    storageId: string;
}> {
    return {
        blob: await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName,
        fileSize: value.fileSize,
        fileType: value.fileType,
        storageId: value.storageId
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    expiresAt: bigint;
    isExpired: boolean;
    isViewed: boolean;
    createdAt: bigint;
    viewedAt: [] | [bigint];
    accessToken: string;
    recipientId: Principal;
    senderId: Principal;
    hasAttachment: boolean;
}): {
    id: string;
    expiresAt: bigint;
    isExpired: boolean;
    isViewed: boolean;
    createdAt: bigint;
    viewedAt?: bigint;
    accessToken: string;
    recipientId: Principal;
    senderId: Principal;
    hasAttachment: boolean;
} {
    return {
        id: value.id,
        expiresAt: value.expiresAt,
        isExpired: value.isExpired,
        isViewed: value.isViewed,
        createdAt: value.createdAt,
        viewedAt: record_opt_to_undefined(from_candid_opt_n23(_uploadFile, _downloadFile, value.viewedAt)),
        accessToken: value.accessToken,
        recipientId: value.recipientId,
        senderId: value.senderId,
        hasAttachment: value.hasAttachment
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flagReason: [] | [string];
    userId: Principal;
    accessAttempts: bigint;
    flaggedAttempts: bigint;
    deviceFingerprints: Array<string>;
    lastAccessTime: bigint;
    isFlagged: boolean;
}): {
    flagReason?: string;
    userId: Principal;
    accessAttempts: bigint;
    flaggedAttempts: bigint;
    deviceFingerprints: Array<string>;
    lastAccessTime: bigint;
    isFlagged: boolean;
} {
    return {
        flagReason: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.flagReason)),
        userId: value.userId,
        accessAttempts: value.accessAttempts,
        flaggedAttempts: value.flaggedAttempts,
        deviceFingerprints: value.deviceFingerprints,
        lastAccessTime: value.lastAccessTime,
        isFlagged: value.isFlagged
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_AccessLog>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<AccessLog>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_MessageSummary>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<MessageSummary>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n20(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: Array<_BehaviorProfile>;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Array<BehaviorProfile>;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_vec_n26(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: boolean;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: boolean;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _BehaviorProfile;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: BehaviorProfile;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_BehaviorProfile_n27(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: string;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: string;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
async function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _MessageView;
} | {
    err: string;
}): Promise<{
    __kind__: "ok";
    ok: MessageView;
} | {
    __kind__: "err";
    err: string;
}> {
    return "ok" in value ? {
        __kind__: "ok",
        ok: await from_candid_MessageView_n10(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MessageSummary>): Array<MessageSummary> {
    return value.map((x)=>from_candid_MessageSummary_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_BehaviorProfile>): Array<BehaviorProfile> {
    return value.map((x)=>from_candid_BehaviorProfile_n27(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FileAttachment_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileAttachment): Promise<_FileAttachment> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileAttachment | null): Promise<[] | [_FileAttachment]> {
    return value === null ? candid_none() : candid_some(await to_candid_FileAttachment_n39(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    blob: ExternalBlob;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    storageId: string;
}): Promise<{
    blob: _ExternalBlob;
    fileName: string;
    fileSize: bigint;
    fileType: string;
    storageId: string;
}> {
    return {
        blob: await to_candid_ExternalBlob_n41(_uploadFile, _downloadFile, value.blob),
        fileName: value.fileName,
        fileSize: value.fileSize,
        fileType: value.fileType,
        storageId: value.storageId
    };
}
function to_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
